name: Docker Build Image - FASTAPI

on:
  push:
    tags:
      - 'v*'

env:
  VERSION: ''
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: downcase repository name
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME@L}" >> "${GITHUB_ENV}"
      - name: extract version
        id: extract_version
        run: |
          echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> "${GITHUB_ENV}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
